### ISSUE TITLE
toolchain build how-to

### ISSUE THREAD

**Issue by cesss** [toltec-dev/toolchain#17]
Do you have any documentation (or a bash script) showing how you build the toolchain? I'd like to build my own toolchain for crosscompiling from Mac (I mean a toolchain for building my apps, not the whole toltec tree).

Thanks!

**Comment by Eeems** [comment]
You can take a look at the workflow files, that would show you what it does. In the end it just calls the build script: https://github.com/toltec-dev/toolchain/blob/v2.x/scripts/build

**Comment by cesss** [comment]
Sorry I didn't reply before, @Eeems ...for the moment I discarded building my own toolchains, because I needed to be able to compile soon, so I'm using the Docker images that rmkit generates.

I'm closing this issue for the moment. Thanks a lot!!

**Comment by Eeems** [comment]
Oh, if you just needed prebuilt images to work with, they are also available for the toltec toolchains.

**Comment by cesss** [comment]
Yes, I know, but my original plan was to build them myself. Then time constraints changed the plan 😄
